// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXkf9z-L0ZvxvtoKc2p0qKXvvjGP3hSW0',
    appId: '1:384467477:web:781f7ef401436eab46c41c',
    messagingSenderId: '384467477',
    projectId: 'sce-project-679d8',
    authDomain: 'sce-project-679d8.firebaseapp.com',
    storageBucket: 'sce-project-679d8.appspot.com',
    measurementId: 'G-R7MHEVQXB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQTim1aGSWHem0xj8747oIt__TDn0DMQc',
    appId: '1:384467477:android:401304925ff6611646c41c',
    messagingSenderId: '384467477',
    projectId: 'sce-project-679d8',
    storageBucket: 'sce-project-679d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD6Bi9fs9WAsOvl9tj2XIN6j90IHNa2BU',
    appId: '1:384467477:ios:c13a368ce70b402346c41c',
    messagingSenderId: '384467477',
    projectId: 'sce-project-679d8',
    storageBucket: 'sce-project-679d8.appspot.com',
    iosBundleId: 'com.example.sceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD6Bi9fs9WAsOvl9tj2XIN6j90IHNa2BU',
    appId: '1:384467477:ios:f74ec32b00a66b3146c41c',
    messagingSenderId: '384467477',
    projectId: 'sce-project-679d8',
    storageBucket: 'sce-project-679d8.appspot.com',
    iosBundleId: 'com.example.sceProject.RunnerTests',
  );
}
